org.gradle.java.home=C:/Program Files/Microsoft/jdk-21.0.12.101-hotspot
org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

## Environment Properties

minecraft_version=1.21.11
minecraft_version_range=[1.21.11,1.22)

neo_version=21.11.0-beta
neo_version_range=[21.11,21.12)

loader_version_range=[4,)

## Mod Properties

mod_id=dimensionblocker
mod_name=DimensionBlocker
mod_license=All Rights Reserved
mod_version=1.0.0

mod_group_id=com.outbackservers

mod_authors=outbackservers
mod_description=Server-side dimension control for The Nether and The End.